### ISSUE TITLE
Notification Support

### ISSUE THREAD

**Issue by HallerPatrick** [HallerPatrick/frosch#16]
Maybe provide a utiliy which triggers a notification on the OS system.
For now I know that this could work with MacOS and iTerm2 https://www.iterm2.com/features.html.

**Comment by dvolgyes** [comment]
I guess the idea is that you want to get notified when your code brakes
(e.g. in the background process, another window, etc.)

Maybe take a look at this for desktop Linux:
https://gitlab.com/hxss/desktop-notify

And this one for other channels (email, instant message,etc.):
https://github.com/liiight/notifiers

**Comment by HallerPatrick** [comment]
Support for all 3 Operating System. It only works if osascript/notify-send/powershell is in path. This should maybe be more robust, especially for linux, to look for alternative notification tools.
I think in most cases osascript (Mac) and powershell (Windows) is fairly standard to have in PATH.
