### ISSUE TITLE
print frosch debug info from an exception handler

### ISSUE THREAD

**Issue by pjz** [HallerPatrick/frosch#20]
I realized there's no way to explicitly make frosch print. eg. I'd like to be able to:

    try:
        foo()
    except SomeError as e:
        frosch.print(e)

to get the nice frosch output while letting my code potentially survive.  I suspect it's probably possible, but just not documented?

**Comment by HallerPatrick** [comment]
This is not possible yet. But a great functionality

**Comment by HallerPatrick** [comment]
Is now included in version 0.1.6
