### ISSUE TITLE
TypeError: hook() got an unexpected keyword argument 'theme'

### ISSUE THREAD

**Issue by dev-mbusch** [HallerPatrick/frosch#23]
Hi there,

just found out about frosch and wanted to give it a try, because I really like the idea!

But I've encountered a problem pretty soon. Using hook() without any config works just fine, but I think I'm just plain dumb or blind or both, but trying to configure hook with the theme argument raises an exception on my side.

![image](https://user-images.githubusercontent.com/39407335/99373044-3f41ad00-28c1-11eb-9b82-0f2b31a2bf93.png)

What am I missing?

**Comment by HallerPatrick** [comment]
I am sorry, I should not put something in the README which is not in a release yet. I will probably push a new version today, so you can use all the features :)

**Comment by dev-mbusch** [comment]
Haha, yeah that's kinda confusing! 

But no worries, it's early days and I was assuming something like that was going on. ;)

**Comment by HallerPatrick** [comment]
Alright new version is released (0.1.6).

`pip install --upgrade frosch` or reinstall and themes should work too! :)
