### ISSUE TITLE
Custom themes?

### ISSUE THREAD

**Issue by subnut** [HallerPatrick/frosch#31]
Is it possible? If yes, how?

**Comment by HallerPatrick** [comment]
You can find it here: https://github.com/HallerPatrick/frosch#themes

```python
from frosch import hook

hook(theme="vim") # Or the theme you want, all of them  are listed in the table
```

**Comment by subnut** [comment]
No no, those are the _available_ themes.

I mean _custom_ themes, which are not available (e.g. _gruvbox_)

**Comment by HallerPatrick** [comment]
Oh sorry. No it is not, frosch just makes a look up of all available themes in [pygments](https://pygments.org). But it is possible to design custom themes for pygments. So it shouldn't be hard to change the interface for custom themes.
