### ISSUE TITLE
Values with large reprs

### ISSUE THREAD

**Issue by alexmojaki** [HallerPatrick/frosch#34]
Example script:

```python
from frosch import hook

hook()
x = list(range(10000))
x/0
```

Output:

```
Traceback (most recent call last):
  File "/home/alex/.config/JetBrains/PyCharm2020.3/scratches/scratch_1099.py", line 5, in <module>
    x/0
TypeError: unsupported operand type(s) for /: 'list' and 'int'

 5 || x / 0
   || │
   || └── x: list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ... this goes on and prints the whole list, up to 9999
```

I suggest https://github.com/alexmojaki/cheap_repr to print truncated reprs without losing too much information.

This also relates to #14

**Comment by HallerPatrick** [comment]
<img width="833" alt="Screenshot 2021-07-30 at 17 00 10" src="https://user-images.githubusercontent.com/22773355/127672403-afcda56d-b234-4e90-8bed-da9be86d7f01.png">

Thank you again, @alexmojaki. 

Works like a charm. 
You are right, that this will also partly help with #14, but this is another issue.
