### ISSUE TITLE
Windows 10 cmd/powershell not working

### ISSUE THREAD

**Issue by smurpau** [HallerPatrick/frosch#7]
Cmd prompt or powershell, natively or in VS code:
![image](https://user-images.githubusercontent.com/59456139/98489378-e56a3300-2281-11eb-9974-e51020355b6e.png)

**Comment by LeMoussel** [comment]
You can use [python-colorlog](https://github.com/borntyping/python-colorlog)  for Log formatting with colors!
`colorlog.ColoredFormatter` is a formatter for use with Python's logging module that outputs records using terminal colors on WIn & Unix.

**Comment by HallerPatrick** [comment]
This should be fixed by now
